-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 16:42:10 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema seven
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seven` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `seven` ;

-- -----------------------------------------------------
-- Table `seven`.`STUDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seven`.`STUDENT` (
  `student_id` INT NOT NULL,
  `student_no` VARCHAR(45) NOT NULL,
  `student_name` VARCHAR(10) NOT NULL,
  `student_sex` VARCHAR(10) NOT NULL,
  `student_age` INT NOT NULL,
  `student_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seven`.`TEACHER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seven`.`TEACHER` (
  `teacher_id` INT NOT NULL,
  `teacher_no` VARCHAR(45) NOT NULL,
  `teacher_name` VARCHAR(10) NOT NULL,
  `teacher_job` VARCHAR(45) NOT NULL,
  `teacher_salary` DOUBLE NOT NULL,
  PRIMARY KEY (`teacher_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seven`.`COURSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seven`.`COURSE` (
  `course_id` INT NOT NULL,
  `teacher_id` INT NOT NULL,
  `course_no` VARCHAR(45) NOT NULL,
  `course_name` VARCHAR(45) NOT NULL,
  `course_score` INT NOT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `teacher_id_fk_course_idx` (`teacher_id` ASC),
  CONSTRAINT `teacher_id_fk_course`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `seven`.`TEACHER` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `seven`.`LEARNING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seven`.`LEARNING` (
  `learning_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `course_achieve` INT NOT NULL,
  PRIMARY KEY (`learning_id`),
  INDEX `student_id_fk_learning_idx` (`student_id` ASC),
  INDEX `course_id_fk_learning_idx` (`course_id` ASC),
  CONSTRAINT `student_id_fk_learning`
    FOREIGN KEY (`student_id`)
    REFERENCES `seven`.`STUDENT` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `course_id_fk_learning`
    FOREIGN KEY (`course_id`)
    REFERENCES `seven`.`COURSE` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
